config:
  read_interval: 0.5
sources:
  - name: ultimeter
    type: ultimeter
    port: /dev/ttyUSB0
    properties:
      - wind_speed
      - wind_dir
      - temperature
    enabled: true
destinations:
  - type: stdout
  - type: jdp
    host: 192.168.1.163
    port: 48000
